# Generated by Django 3.1.3 on 2020-11-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201114_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='thumbnail',
            new_name='project_image',
        ),
    ]
