# Generated by Django 3.1.2 on 2020-10-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201022_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photos',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
