# Generated by Django 3.1.3 on 2020-11-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201114_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
