# Generated by Django 3.1.2 on 2020-11-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201028_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('quote_author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='tagline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='quotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='quotes', to='projects.Quotes'),
        ),
    ]
