# Generated by Django 3.1.3 on 2020-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201119_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
