# Generated by Django 3.1.2 on 2020-11-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201104_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name_plural': 'Quotes'},
        ),
    ]
