# Generated by Django 4.0.4 on 2022-04-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201128_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='projects.categories'),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.photos'),
        ),
    ]
