# Generated by Django 3.1.2 on 2020-11-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201104_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='website_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
