# Generated by Django 3.1.3 on 2020-11-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201110_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='blog',
        ),
    ]
