# Generated by Django 3.1.3 on 2020-11-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201111_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='blog',
            new_name='description',
        ),
    ]
